// Code generated by protoc-gen-go.
// source: mqttaudio.proto
// DO NOT EDIT!

/*
Package icd is a generated protocol buffer package.

It is generated from these files:
	mqttaudio.proto

It has these top-level messages:
	AudioData
*/
package icd

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type AudioData struct {
	Channels         *int32  `protobuf:"varint,1,opt,name=channels" json:"channels,omitempty"`
	FrameLength      *int32  `protobuf:"varint,2,opt,name=frame_length" json:"frame_length,omitempty"`
	SamplingRate     *int32  `protobuf:"varint,3,opt,name=sampling_rate" json:"sampling_rate,omitempty"`
	Bitrate          *int32  `protobuf:"varint,4,opt,name=bitrate" json:"bitrate,omitempty"`
	Audio            []byte  `protobuf:"bytes,5,opt,name=audio" json:"audio,omitempty"`
	Audio2           []int32 `protobuf:"zigzag32,6,rep,name=audio2" json:"audio2,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *AudioData) Reset()                    { *m = AudioData{} }
func (m *AudioData) String() string            { return proto.CompactTextString(m) }
func (*AudioData) ProtoMessage()               {}
func (*AudioData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *AudioData) GetChannels() int32 {
	if m != nil && m.Channels != nil {
		return *m.Channels
	}
	return 0
}

func (m *AudioData) GetFrameLength() int32 {
	if m != nil && m.FrameLength != nil {
		return *m.FrameLength
	}
	return 0
}

func (m *AudioData) GetSamplingRate() int32 {
	if m != nil && m.SamplingRate != nil {
		return *m.SamplingRate
	}
	return 0
}

func (m *AudioData) GetBitrate() int32 {
	if m != nil && m.Bitrate != nil {
		return *m.Bitrate
	}
	return 0
}

func (m *AudioData) GetAudio() []byte {
	if m != nil {
		return m.Audio
	}
	return nil
}

func (m *AudioData) GetAudio2() []int32 {
	if m != nil {
		return m.Audio2
	}
	return nil
}

func init() {
	proto.RegisterType((*AudioData)(nil), "icd.AudioData")
}

var fileDescriptor0 = []byte{
	// 147 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x1c, 0xcd, 0xbf, 0x0e, 0x82, 0x30,
	0x10, 0x80, 0xf1, 0x60, 0x2d, 0xea, 0x05, 0x44, 0x1b, 0x4d, 0x3a, 0x12, 0x27, 0x26, 0x07, 0xdf,
	0xc0, 0xc4, 0xf7, 0x20, 0x27, 0x54, 0x68, 0xd2, 0x3f, 0x58, 0xce, 0xc5, 0xa7, 0x57, 0x6e, 0xfc,
	0x7e, 0xcb, 0x07, 0x95, 0x7f, 0x13, 0xe1, 0xa7, 0xb7, 0xf1, 0x3a, 0xa5, 0x48, 0x51, 0x09, 0xdb,
	0xf5, 0x97, 0x2f, 0xec, 0xee, 0x8b, 0x3d, 0x90, 0x50, 0x1d, 0x60, 0xdb, 0x8d, 0x18, 0x82, 0x71,
	0xb3, 0xce, 0xea, 0xac, 0x91, 0xea, 0x04, 0xc5, 0x2b, 0xa1, 0x37, 0xad, 0x33, 0x61, 0xa0, 0x51,
	0xaf, 0x58, 0xcf, 0x50, 0xce, 0xe8, 0x27, 0x67, 0xc3, 0xd0, 0x26, 0x24, 0xa3, 0x05, 0x73, 0x05,
	0x9b, 0xa7, 0x25, 0x86, 0x35, 0x43, 0x09, 0x92, 0x87, 0x5a, 0xfe, 0xb3, 0x50, 0x7b, 0xc8, 0x39,
	0x6f, 0x3a, 0xaf, 0x45, 0x73, 0xfc, 0x05, 0x00, 0x00, 0xff, 0xff, 0x4c, 0x82, 0x9c, 0x62, 0x92,
	0x00, 0x00, 0x00,
}
