// Code generated by protoc-gen-gogo.
// source: audio.proto
// DO NOT EDIT!

/*
	Package shackbus_audio is a generated protocol buffer package.

	It is generated from these files:
		audio.proto

	It has these top-level messages:
		None
		Error
		Capabilities
		PingPong
		Frame
		State
*/
package shackbus_audio

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Channels int32

const (
	Channels_unknown Channels = 0
	Channels_mono    Channels = 1
	Channels_stereo  Channels = 2
)

var Channels_name = map[int32]string{
	0: "unknown",
	1: "mono",
	2: "stereo",
}
var Channels_value = map[string]int32{
	"unknown": 0,
	"mono":    1,
	"stereo":  2,
}

func (x Channels) String() string {
	return proto.EnumName(Channels_name, int32(x))
}
func (Channels) EnumDescriptor() ([]byte, []int) { return fileDescriptorAudio, []int{0} }

type Codec int32

const (
	Codec_none Codec = 0
	Codec_opus Codec = 1
	Codec_pcm  Codec = 2
)

var Codec_name = map[int32]string{
	0: "none",
	1: "opus",
	2: "pcm",
}
var Codec_value = map[string]int32{
	"none": 0,
	"opus": 1,
	"pcm":  2,
}

func (x Codec) String() string {
	return proto.EnumName(Codec_name, int32(x))
}
func (Codec) EnumDescriptor() ([]byte, []int) { return fileDescriptorAudio, []int{1} }

type None struct {
}

func (m *None) Reset()                    { *m = None{} }
func (m *None) String() string            { return proto.CompactTextString(m) }
func (*None) ProtoMessage()               {}
func (*None) Descriptor() ([]byte, []int) { return fileDescriptorAudio, []int{0} }

type Error struct {
	Error string `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
}

func (m *Error) Reset()                    { *m = Error{} }
func (m *Error) String() string            { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()               {}
func (*Error) Descriptor() ([]byte, []int) { return fileDescriptorAudio, []int{1} }

func (m *Error) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type Capabilities struct {
	Name            string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	RxStreamAddress string `protobuf:"bytes,2,opt,name=rx_stream_address,json=rxStreamAddress,proto3" json:"rx_stream_address,omitempty"`
	TxStreamAddress string `protobuf:"bytes,3,opt,name=tx_stream_address,json=txStreamAddress,proto3" json:"tx_stream_address,omitempty"`
}

func (m *Capabilities) Reset()                    { *m = Capabilities{} }
func (m *Capabilities) String() string            { return proto.CompactTextString(m) }
func (*Capabilities) ProtoMessage()               {}
func (*Capabilities) Descriptor() ([]byte, []int) { return fileDescriptorAudio, []int{2} }

func (m *Capabilities) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Capabilities) GetRxStreamAddress() string {
	if m != nil {
		return m.RxStreamAddress
	}
	return ""
}

func (m *Capabilities) GetTxStreamAddress() string {
	if m != nil {
		return m.TxStreamAddress
	}
	return ""
}

type PingPong struct {
	Ping int64 `protobuf:"varint,1,opt,name=ping,proto3" json:"ping,omitempty"`
}

func (m *PingPong) Reset()                    { *m = PingPong{} }
func (m *PingPong) String() string            { return proto.CompactTextString(m) }
func (*PingPong) ProtoMessage()               {}
func (*PingPong) Descriptor() ([]byte, []int) { return fileDescriptorAudio, []int{3} }

func (m *PingPong) GetPing() int64 {
	if m != nil {
		return m.Ping
	}
	return 0
}

// Audio frame consisting of the raw audio byte array + metadata
type Frame struct {
	Codec        Codec    `protobuf:"varint,1,opt,name=codec,proto3,enum=shackbus.audio.Codec" json:"codec,omitempty"`
	Channels     Channels `protobuf:"varint,2,opt,name=channels,proto3,enum=shackbus.audio.Channels" json:"channels,omitempty"`
	FrameLength  int32    `protobuf:"varint,3,opt,name=frame_length,json=frameLength,proto3" json:"frame_length,omitempty"`
	SamplingRate int32    `protobuf:"varint,4,opt,name=sampling_rate,json=samplingRate,proto3" json:"sampling_rate,omitempty"`
	BitDepth     int32    `protobuf:"varint,5,opt,name=bit_depth,json=bitDepth,proto3" json:"bit_depth,omitempty"`
	Data         []byte   `protobuf:"bytes,6,opt,name=data,proto3" json:"data,omitempty"`
	UserId       string   `protobuf:"bytes,8,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (m *Frame) Reset()                    { *m = Frame{} }
func (m *Frame) String() string            { return proto.CompactTextString(m) }
func (*Frame) ProtoMessage()               {}
func (*Frame) Descriptor() ([]byte, []int) { return fileDescriptorAudio, []int{4} }

func (m *Frame) GetCodec() Codec {
	if m != nil {
		return m.Codec
	}
	return Codec_none
}

func (m *Frame) GetChannels() Channels {
	if m != nil {
		return m.Channels
	}
	return Channels_unknown
}

func (m *Frame) GetFrameLength() int32 {
	if m != nil {
		return m.FrameLength
	}
	return 0
}

func (m *Frame) GetSamplingRate() int32 {
	if m != nil {
		return m.SamplingRate
	}
	return 0
}

func (m *Frame) GetBitDepth() int32 {
	if m != nil {
		return m.BitDepth
	}
	return 0
}

func (m *Frame) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Frame) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type State struct {
	RxOn   bool   `protobuf:"varint,1,opt,name=rx_on,json=rxOn,proto3" json:"rx_on,omitempty"`
	TxOn   bool   `protobuf:"varint,2,opt,name=tx_on,json=txOn,proto3" json:"tx_on,omitempty"`
	TxUser string `protobuf:"bytes,3,opt,name=tx_user,json=txUser,proto3" json:"tx_user,omitempty"`
}

func (m *State) Reset()                    { *m = State{} }
func (m *State) String() string            { return proto.CompactTextString(m) }
func (*State) ProtoMessage()               {}
func (*State) Descriptor() ([]byte, []int) { return fileDescriptorAudio, []int{5} }

func (m *State) GetRxOn() bool {
	if m != nil {
		return m.RxOn
	}
	return false
}

func (m *State) GetTxOn() bool {
	if m != nil {
		return m.TxOn
	}
	return false
}

func (m *State) GetTxUser() string {
	if m != nil {
		return m.TxUser
	}
	return ""
}

func init() {
	proto.RegisterType((*None)(nil), "shackbus.audio.None")
	proto.RegisterType((*Error)(nil), "shackbus.audio.Error")
	proto.RegisterType((*Capabilities)(nil), "shackbus.audio.Capabilities")
	proto.RegisterType((*PingPong)(nil), "shackbus.audio.PingPong")
	proto.RegisterType((*Frame)(nil), "shackbus.audio.Frame")
	proto.RegisterType((*State)(nil), "shackbus.audio.State")
	proto.RegisterEnum("shackbus.audio.Channels", Channels_name, Channels_value)
	proto.RegisterEnum("shackbus.audio.Codec", Codec_name, Codec_value)
}
func (m *None) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *None) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	return i, nil
}

func (m *Error) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Error) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Error) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintAudio(dAtA, i, uint64(len(m.Error)))
		i += copy(dAtA[i:], m.Error)
	}
	return i, nil
}

func (m *Capabilities) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Capabilities) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Name) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintAudio(dAtA, i, uint64(len(m.Name)))
		i += copy(dAtA[i:], m.Name)
	}
	if len(m.RxStreamAddress) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintAudio(dAtA, i, uint64(len(m.RxStreamAddress)))
		i += copy(dAtA[i:], m.RxStreamAddress)
	}
	if len(m.TxStreamAddress) > 0 {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintAudio(dAtA, i, uint64(len(m.TxStreamAddress)))
		i += copy(dAtA[i:], m.TxStreamAddress)
	}
	return i, nil
}

func (m *PingPong) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PingPong) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Ping != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintAudio(dAtA, i, uint64(m.Ping))
	}
	return i, nil
}

func (m *Frame) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Frame) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Codec != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintAudio(dAtA, i, uint64(m.Codec))
	}
	if m.Channels != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintAudio(dAtA, i, uint64(m.Channels))
	}
	if m.FrameLength != 0 {
		dAtA[i] = 0x18
		i++
		i = encodeVarintAudio(dAtA, i, uint64(m.FrameLength))
	}
	if m.SamplingRate != 0 {
		dAtA[i] = 0x20
		i++
		i = encodeVarintAudio(dAtA, i, uint64(m.SamplingRate))
	}
	if m.BitDepth != 0 {
		dAtA[i] = 0x28
		i++
		i = encodeVarintAudio(dAtA, i, uint64(m.BitDepth))
	}
	if len(m.Data) > 0 {
		dAtA[i] = 0x32
		i++
		i = encodeVarintAudio(dAtA, i, uint64(len(m.Data)))
		i += copy(dAtA[i:], m.Data)
	}
	if len(m.UserId) > 0 {
		dAtA[i] = 0x42
		i++
		i = encodeVarintAudio(dAtA, i, uint64(len(m.UserId)))
		i += copy(dAtA[i:], m.UserId)
	}
	return i, nil
}

func (m *State) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *State) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.RxOn {
		dAtA[i] = 0x8
		i++
		if m.RxOn {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i++
	}
	if m.TxOn {
		dAtA[i] = 0x10
		i++
		if m.TxOn {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i++
	}
	if len(m.TxUser) > 0 {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintAudio(dAtA, i, uint64(len(m.TxUser)))
		i += copy(dAtA[i:], m.TxUser)
	}
	return i, nil
}

func encodeFixed64Audio(dAtA []byte, offset int, v uint64) int {
	dAtA[offset] = uint8(v)
	dAtA[offset+1] = uint8(v >> 8)
	dAtA[offset+2] = uint8(v >> 16)
	dAtA[offset+3] = uint8(v >> 24)
	dAtA[offset+4] = uint8(v >> 32)
	dAtA[offset+5] = uint8(v >> 40)
	dAtA[offset+6] = uint8(v >> 48)
	dAtA[offset+7] = uint8(v >> 56)
	return offset + 8
}
func encodeFixed32Audio(dAtA []byte, offset int, v uint32) int {
	dAtA[offset] = uint8(v)
	dAtA[offset+1] = uint8(v >> 8)
	dAtA[offset+2] = uint8(v >> 16)
	dAtA[offset+3] = uint8(v >> 24)
	return offset + 4
}
func encodeVarintAudio(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *None) Size() (n int) {
	var l int
	_ = l
	return n
}

func (m *Error) Size() (n int) {
	var l int
	_ = l
	l = len(m.Error)
	if l > 0 {
		n += 1 + l + sovAudio(uint64(l))
	}
	return n
}

func (m *Capabilities) Size() (n int) {
	var l int
	_ = l
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovAudio(uint64(l))
	}
	l = len(m.RxStreamAddress)
	if l > 0 {
		n += 1 + l + sovAudio(uint64(l))
	}
	l = len(m.TxStreamAddress)
	if l > 0 {
		n += 1 + l + sovAudio(uint64(l))
	}
	return n
}

func (m *PingPong) Size() (n int) {
	var l int
	_ = l
	if m.Ping != 0 {
		n += 1 + sovAudio(uint64(m.Ping))
	}
	return n
}

func (m *Frame) Size() (n int) {
	var l int
	_ = l
	if m.Codec != 0 {
		n += 1 + sovAudio(uint64(m.Codec))
	}
	if m.Channels != 0 {
		n += 1 + sovAudio(uint64(m.Channels))
	}
	if m.FrameLength != 0 {
		n += 1 + sovAudio(uint64(m.FrameLength))
	}
	if m.SamplingRate != 0 {
		n += 1 + sovAudio(uint64(m.SamplingRate))
	}
	if m.BitDepth != 0 {
		n += 1 + sovAudio(uint64(m.BitDepth))
	}
	l = len(m.Data)
	if l > 0 {
		n += 1 + l + sovAudio(uint64(l))
	}
	l = len(m.UserId)
	if l > 0 {
		n += 1 + l + sovAudio(uint64(l))
	}
	return n
}

func (m *State) Size() (n int) {
	var l int
	_ = l
	if m.RxOn {
		n += 2
	}
	if m.TxOn {
		n += 2
	}
	l = len(m.TxUser)
	if l > 0 {
		n += 1 + l + sovAudio(uint64(l))
	}
	return n
}

func sovAudio(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozAudio(x uint64) (n int) {
	return sovAudio(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *None) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAudio
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: None: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: None: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipAudio(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthAudio
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Error) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAudio
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Error: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Error: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Error", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAudio
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAudio
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Error = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipAudio(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthAudio
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Capabilities) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAudio
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Capabilities: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Capabilities: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAudio
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAudio
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RxStreamAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAudio
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAudio
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RxStreamAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TxStreamAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAudio
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAudio
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TxStreamAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipAudio(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthAudio
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PingPong) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAudio
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PingPong: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PingPong: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Ping", wireType)
			}
			m.Ping = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAudio
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Ping |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipAudio(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthAudio
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Frame) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAudio
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Frame: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Frame: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Codec", wireType)
			}
			m.Codec = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAudio
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Codec |= (Codec(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Channels", wireType)
			}
			m.Channels = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAudio
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Channels |= (Channels(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FrameLength", wireType)
			}
			m.FrameLength = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAudio
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.FrameLength |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SamplingRate", wireType)
			}
			m.SamplingRate = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAudio
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SamplingRate |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BitDepth", wireType)
			}
			m.BitDepth = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAudio
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BitDepth |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Data", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAudio
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthAudio
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Data = append(m.Data[:0], dAtA[iNdEx:postIndex]...)
			if m.Data == nil {
				m.Data = []byte{}
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UserId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAudio
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAudio
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UserId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipAudio(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthAudio
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *State) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAudio
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: State: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: State: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RxOn", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAudio
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.RxOn = bool(v != 0)
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TxOn", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAudio
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.TxOn = bool(v != 0)
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TxUser", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAudio
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAudio
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TxUser = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipAudio(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthAudio
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipAudio(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowAudio
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowAudio
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowAudio
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthAudio
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowAudio
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipAudio(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthAudio = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowAudio   = fmt.Errorf("proto: integer overflow")
)

func init() { proto.RegisterFile("audio.proto", fileDescriptorAudio) }

var fileDescriptorAudio = []byte{
	// 518 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x9c, 0x93, 0xcf, 0x6e, 0xd3, 0x40,
	0x10, 0xc6, 0xeb, 0xd4, 0x76, 0xdc, 0x49, 0x48, 0xcd, 0x52, 0x54, 0xab, 0x40, 0x54, 0x0c, 0x87,
	0x2a, 0x88, 0x1c, 0x02, 0x17, 0x7a, 0x83, 0x52, 0x10, 0x08, 0x41, 0xe5, 0x88, 0xb3, 0xb5, 0x89,
	0x87, 0x64, 0xd5, 0x64, 0xd7, 0xda, 0x9d, 0x80, 0xc5, 0x91, 0xa7, 0xe0, 0x91, 0x38, 0xf2, 0x08,
	0x28, 0xbc, 0x06, 0x07, 0xb4, 0xeb, 0x04, 0x11, 0xa2, 0x5e, 0xb8, 0xcd, 0x7e, 0xf3, 0x5b, 0xcf,
	0x9f, 0xfd, 0x0c, 0x2d, 0xbe, 0x28, 0x84, 0xea, 0x97, 0x5a, 0x91, 0x62, 0x1d, 0x33, 0xe5, 0xe3,
	0xcb, 0xd1, 0xc2, 0xf4, 0x9d, 0x9a, 0x86, 0xe0, 0xbf, 0x55, 0x12, 0xd3, 0x3b, 0x10, 0x9c, 0x6b,
	0xad, 0x34, 0x3b, 0x80, 0x00, 0x6d, 0x90, 0x78, 0xc7, 0xde, 0xc9, 0x5e, 0x56, 0x1f, 0xd2, 0xcf,
	0xd0, 0x3e, 0xe3, 0x25, 0x1f, 0x89, 0x99, 0x20, 0x81, 0x86, 0x31, 0xf0, 0x25, 0x9f, 0xe3, 0x0a,
	0x72, 0x31, 0xeb, 0xc1, 0x75, 0x5d, 0xe5, 0x86, 0x34, 0xf2, 0x79, 0xce, 0x8b, 0x42, 0xa3, 0x31,
	0x49, 0xc3, 0x01, 0xfb, 0xba, 0x1a, 0x3a, 0xfd, 0x69, 0x2d, 0x5b, 0x96, 0xb6, 0xd8, 0xdd, 0x9a,
	0xa5, 0x4d, 0x36, 0xed, 0x42, 0x74, 0x21, 0xe4, 0xe4, 0x42, 0xc9, 0x89, 0xad, 0x5b, 0x0a, 0x39,
	0x71, 0x75, 0x77, 0x33, 0x17, 0xa7, 0xbf, 0x3c, 0x08, 0x5e, 0x68, 0xdb, 0xc1, 0x03, 0x08, 0xc6,
	0xaa, 0xc0, 0xb1, 0x4b, 0x77, 0x06, 0x37, 0xfb, 0x9b, 0xc3, 0xf6, 0xcf, 0x6c, 0x32, 0xab, 0x19,
	0xf6, 0x18, 0xa2, 0xf1, 0x94, 0x4b, 0x89, 0xb3, 0xba, 0xcb, 0xce, 0x20, 0xd9, 0xe2, 0x57, 0xf9,
	0xec, 0x0f, 0xc9, 0xee, 0x42, 0xfb, 0x83, 0xad, 0x95, 0xcf, 0x50, 0x4e, 0x68, 0xea, 0x7a, 0x0e,
	0xb2, 0x96, 0xd3, 0xde, 0x38, 0x89, 0xdd, 0x83, 0x6b, 0x86, 0xcf, 0xcb, 0x99, 0x90, 0x93, 0x5c,
	0x73, 0xc2, 0xc4, 0x77, 0x4c, 0x7b, 0x2d, 0x66, 0x9c, 0x90, 0xdd, 0x82, 0xbd, 0x91, 0xa0, 0xbc,
	0xc0, 0x92, 0xa6, 0x49, 0xe0, 0x80, 0x68, 0x24, 0xe8, 0xb9, 0x3d, 0xdb, 0x29, 0x0b, 0x4e, 0x3c,
	0x09, 0x8f, 0xbd, 0x93, 0x76, 0xe6, 0x62, 0x76, 0x08, 0xcd, 0x85, 0x41, 0x9d, 0x8b, 0x22, 0x89,
	0xdc, 0x9e, 0x42, 0x7b, 0x7c, 0x55, 0xa4, 0xaf, 0x21, 0x18, 0x92, 0xfd, 0xe4, 0x0d, 0x08, 0x74,
	0x95, 0x2b, 0xe9, 0xa6, 0x8f, 0x32, 0x5f, 0x57, 0xef, 0xa4, 0x15, 0xc9, 0x89, 0x8d, 0x5a, 0x24,
	0x2b, 0x1e, 0x42, 0x93, 0xaa, 0xdc, 0xde, 0x5f, 0xed, 0x3c, 0xa4, 0xea, 0xbd, 0x41, 0xdd, 0x7b,
	0x08, 0xd1, 0x7a, 0x66, 0xd6, 0x82, 0xe6, 0x42, 0x5e, 0x4a, 0xf5, 0x49, 0xc6, 0x3b, 0x2c, 0x02,
	0x7f, 0xae, 0xa4, 0x8a, 0x3d, 0x06, 0x10, 0x1a, 0x42, 0x8d, 0x2a, 0x6e, 0xf4, 0xee, 0x43, 0xe0,
	0x56, 0x6a, 0xd3, 0x52, 0x49, 0xac, 0x41, 0x55, 0x2e, 0x4c, 0xec, 0xb1, 0x26, 0xec, 0x96, 0xe3,
	0x79, 0xdc, 0x18, 0x7c, 0x69, 0x40, 0x38, 0x44, 0xfd, 0x11, 0x35, 0x3b, 0x87, 0xfd, 0x97, 0x48,
	0x1b, 0x4e, 0x3a, 0xf8, 0x77, 0xe9, 0xd6, 0x8e, 0x47, 0xb7, 0xb7, 0x9e, 0xe2, 0xef, 0x3b, 0xa7,
	0xd0, 0x1a, 0x12, 0xd7, 0x54, 0xfb, 0xe4, 0x8a, 0x4f, 0x6c, 0xbd, 0x7e, 0xed, 0xef, 0x27, 0x00,
	0x43, 0x52, 0xe5, 0xff, 0x5c, 0x3d, 0x05, 0xdf, 0x1a, 0x91, 0x6d, 0xf9, 0x64, 0x6d, 0xcf, 0xa3,
	0x2b, 0x33, 0xcf, 0xe2, 0x6f, 0xcb, 0xae, 0xf7, 0x7d, 0xd9, 0xf5, 0x7e, 0x2c, 0xbb, 0xde, 0xd7,
	0x9f, 0xdd, 0x9d, 0x51, 0xe8, 0x7e, 0xc8, 0x47, 0xbf, 0x03, 0x00, 0x00, 0xff, 0xff, 0x46, 0x47,
	0x4d, 0x36, 0x9f, 0x03, 0x00, 0x00,
}
